server:
  port: ${PORT:10000}   # Render usa porta 10000

spring:
  application:
    name: voting-system-api-gateway
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000,https://voting-frontend-blpn.onrender.com"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      httpclient:
        connect-timeout: 10000
        response-timeout: 60s

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:https://voting-system-discovery.onrender.com/eureka/}
    registry-fetch-interval-seconds: 5
  instance:
    appname: voting-system-api-gateway
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always